### ISSUE TITLE
Custom HTML/CSS/JS

### ISSUE THREAD

**Issue by patrickdappollonio** [patrickdappollonio/http-server#14]
More than once I've been asked to offer an option where people can inject:

### Custom CSS

The idea here is to be able to modify the appearance of the page using CSS to allow whitelabeling or customizations that would provide companies/people with branding.

Some suggestions heard were like providing the option to use a CSS that's already part of the directory `http-server` serves, since it'll provide the benefit that it can be read from its source without having to add too much code, but then that also brings the request of being able to hide given file from the directory listing to provide a "clean" view of the files without configuration files.

Other options gauged are below.

### Custom JS

Not sure if we would ever implement something like this directly, mostly because of potential security implications. Not that with CSS only you could shoot yourself in the foot, but it's far less likely.

The same suggestions from the custom CSS have also been said for JS.

### Custom HTML

Some people have requested the ability to be able to write content to the page template, either right after the navbar on top or at the end of the content in some sort of disclaimer.

My take on this one is that while it proposes an interesting idea, it's difficult to pull. Not only due to security implications, but also due to the fact most people would not like to see these settings.

### Suggested approach and context

Adding all of the above features will certainly move the app away from its intended behaviour. Not only `http-server` is already 2.8 Mb due to Go's overhead and packages used, but it would certainly grow larger for users that really might not need these features at all -- I mentioned in another issue I've seen uses of `http-server` in the wild, but very unlikely to serve directory listings.

Besides, there currently is an "unsafe" option called `$FILE_SERVER_BANNER` which allows you to set a banner at the top of the page, and it does not stop you from using any HTML, CSS or JS. I've been looking to change its behaviour to only support a limited subset of HTML like `<strong>`, `<a>`, `<em>` and `<u>` and remove the rest, but that would require importing a library for such effect.

I could commit however to something like this: provide a configuration option in a human-readable language like YAML -- which might not be the best, but it's approachable and other configuration languages like TOML or HCL are a bit less friendly and scarier to use for non-tech-savvy people.

The YAML could look like this:

```yaml
path: "."                   # akin to $FILE_SERVER_PATH
title: "HTTP File Server"   # akin to $FILE_SERVER_TITLE
pathPrefix: "/"             # akin to $FILE_SERVER_PATH_PREFIX
hidePromoLinks: false       # akin to $FILE_SERVER_HIDE_LINKS 
enableCORS: true            # akin to $FILE_SERVER_CORS 
username: ""                # akin to $FILE_SERVER_USERNAME
passwordString: ""          # akin to $FILE_SERVER_PASSWORD

# the following is akin to $FILE_SERVER_BANNER
banner: |
  <strong>Info</strong> Here's my <em>info message</em>. Enjoy!

# the following would add custom CSS
css: |
  body {
    background-color: red;
  }
```

This file would convert all the environment variable settings into a file that would be loaded from the current path, named `.http-server-config.yaml` (starting with a dot). This file **would not be shown** in directory listing mode if the name is an exact match -- since it contains a password, and direct attempt to access it -- like attempting to type it in the URL -- would result in a Forbidden request.

The file would provide at least some CSS configuration options, and the custom CSS option would be offered both as an env var as well as a flag.

Looking for opinions!
