### ISSUE TITLE
Issue displaying correctly behind nginx proxy manager custom locations

### ISSUE THREAD

**Issue by sloniupl** [patrickdappollonio/http-server#24]
I'm using this great project to display openwrt images i have downloaded for my routers.
Version 1.0.3 is working correctly.
My docker compose:
```
#source: https://github.com/patrickdappollonio/http-server 
version: '2'

services:
  http-server:
    image: ghcr.io/patrickdappollonio/docker-http-server:v1.0.3
    ports:
      - 8005:5000
    volumes:
      - /mnt/dane/container/openwrt:/html
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

How it looks on version 1.0.3:
![image](https://user-images.githubusercontent.com/5970551/204100852-4f18efce-9635-4dd8-91f8-57734ccfd849.png)
After changing to newest version image: ghcr.io/patrickdappollonio/docker-http-server:latest it is not working anymore when used with ngix proxy manager as a custom location:
![image](https://user-images.githubusercontent.com/5970551/204100908-ed62b2d7-5ddb-4a6f-8c3b-eb3c3a3d4f02.png)

It looks like that:
![image](https://user-images.githubusercontent.com/5970551/204100920-d8ee49ea-4ddf-42d0-8d01-5c2598010b66.png)

It works correctly when opening locally http://192.168.1.100:8005/
![image](https://user-images.githubusercontent.com/5970551/204100948-de90a3b0-8464-4aae-a504-809bd609a557.png)

logs don't show anything strange:
```
2022/11/26 17:17:04 SETUP:
2022/11/26 17:17:04  > Configured to use port: 5000
2022/11/26 17:17:04  > Serving path: ./
2022/11/26 17:17:04 Starting server...
2022/11/26 17:17:10 GET "/openwrt/" -- HTTP/1.1 200 OK (served in 587.454µs; 28 bytes)

```

**Comment by patrickdappollonio** [comment]
Hello!

It seems you're running the container from a subpath, like `example.com/openwrt`. Try setting `--pathprefix` to `--pathprefix=/openwrt/`

Let me know how it works!

**Comment by sloniupl** [comment]
Thanks for quick reply, i'm a beginner with docker compose and i don't know how to pass --pathprefix in compose file (YAML).

**Comment by patrickdappollonio** [comment]
No worries, that's what these questions are here for!

This should work:

```
version: '2'

services:
  http-server:
    image: ghcr.io/patrickdappollonio/docker-http-server:latest
    command: | 
        http-server --pathprefix="/openwrt/" --path="/html"
    ports:
      - 8005:5000
    volumes:
      - /mnt/dane/container/openwrt:/html
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

I set two things for these:

* The path prefix (since you're serving the container under `example.com/openwrt/`
* The path set to `/html` since that's where you're mounting these files
  * You shouldn't need this because I am setting the container's directory to `/html` too but it's better IMHO to be declarative

Let me know how/if this works!

**Comment by sloniupl** [comment]
Thanks, still not working.
Logs when accessing it locally (green) and via example.com/openwrt/ (red)
![image](https://user-images.githubusercontent.com/5970551/204103145-eb845970-5ce0-4edb-9a96-0f49c3f449e2.png)

**Comment by patrickdappollonio** [comment]
Would you mind sharing the hostname you use to connect to it as you pass it in the browser?

I suspect your nginx proxy manager might be sending to http-server the original host as the host. The urls in the log seem correct now.

**Comment by sloniupl** [comment]
Sure https://sloniupl.eu/openwrt/

**Comment by patrickdappollonio** [comment]
Let me try a few things, set up proxy manager and see what the issue might be. I'll circle back to you asap!

**Comment by patrickdappollonio** [comment]
Hey @sloniupl, happy holidays!

I took a look at this (and apologizes for the delay). I spun up a server with Nginx Proxy Manager, added a new "Proxy Hosts":

![image](https://user-images.githubusercontent.com/930925/209416646-fe0622e2-795a-4eef-bf4b-c8ff17edadb6.png)

Note here that `nip.io` is a convenience endpoint to generate hosts that self-resolve. In this case, if I type `app.127.0.0.1.nip.io` it will resolve to my local machine to ports 80/443 which is where Nginx Proxy Manager is running.

Then I added the configuration tab you had. Note one tiny note here:

![image](https://user-images.githubusercontent.com/930925/209416669-af7c0cdc-dbce-4aee-b63e-f97ed332b278.png)

The message right below says that if you want to "pass" a sub-folder forwarding, you need to add it here.

My docker-compose looks like this:

```yaml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  http-server:
    image: ghcr.io/patrickdappollonio/docker-http-server:latest
    command: |
      http-server --pathprefix="/openwrt/"
    ports:
      - 5000:5000
    volumes:
      - ./:/html
    restart: always
```

Note the following:

* I am running `http-server` in the same compose. In practice this doesn't matter as long as you don't create a custom network between the services, then they won't be able to "discover" each other.
* Since I defined an app called `http-server`, I know any other Docker container can access this container using this hostname, so `http://http-server:5000` here will resolve from the Nginx Proxy Manager automatically to the local container running `http-server`

That's why in my 2nd configuration tab I did not put an IP address like you did (you put `192.168.1.100`, I made Docker resolve itself). In practice, this doesn't matter though and I was able to achieve the same outcome using my loopback address.

The outcome? Both the content and the page load correctly:

![image](https://user-images.githubusercontent.com/930925/209416752-3ba97743-b20f-43f1-9c81-c28eddf50c04.png)

Now granted, your setup might be different than mine, and for example, you might have cases where you must specify a network in your docker-compose file. If that's the case, I'm afraid that kind of setup is far out from being support from `http-server` but more a question for the Nginx Proxy Manager folks.

The trick here for me was to set the "Forward Hostname / IP" to include the path prefix we selected.

The reason why this worked in the past was because the assets are loaded from 3rd parties (the open internet) while in the latest version they all load locally. While old versions work, making links between resources would've not worked (granted though, that feature wasn't there before so no harm done).

Hope this helps, apologies again for the long wait! Keep us posted.
