### ISSUE TITLE
Cobra flags fed by environment variables

### ISSUE THREAD

**Issue by dcgsteve** [patrickdappollonio/http-server#25]
My understanding was that you could inject Cobra flags by setting environment variables to match the flag name.
I'm doing that with this container, for instance:

```
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: PATH
          value: /files
        - name: TITLE
          value: Public Files Test
        image: ghcr.io/patrickdappollonio/docker-http-server:latest
```

All seems to work ok apart from PATH  - the port and title are updated ok but the PATH still defaults to /

Am I doing something wrong?

**Comment by patrickdappollonio** [comment]
Hey @dcgsteve!

I'm not entirely sure... I downloaded the latest version of the software and ran this, changing the default port to `1234`:

```bash
$ PORT=1234 http-server
2023/01/19 01:53:25 SETUP:
2023/01/19 01:53:25  > Configured to use port: 1234
2023/01/19 01:53:25  > Serving path: ./
2023/01/19 01:53:25 Starting server...
```

In another terminal then I made this request:

```bash
$ curl -v -s localhost:1234 1> /dev/null
*   Trying 127.0.0.1:1234...
* Connected to localhost (127.0.0.1) port 1234 (#0)
> GET / HTTP/1.1
> Host: localhost:1234
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 19 Jan 2023 06:53:27 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
<
{ [3972 bytes data]
* Connection #0 to host localhost left intact
```

I can correctly see the page, as you can see, with a 200 OK.

I then wanted to check the container image hosted in GHCR, to mimic what you are doing, so I ran this, with `-e PORT=1234` and also `--network=host` so I can connect to it:

```bash
$ docker run -e PORT=1234 --network=host ghcr.io/patrickdappollonio/docker-http-server:v2.0.0
2023/01/19 06:56:34 SETUP:
2023/01/19 06:56:34  > Configured to use port: 1234
2023/01/19 06:56:34  > Serving path: ./
2023/01/19 06:56:34 Starting server...
```

Same as before, you can see the log saying "Configured to use port: 1234" in the output and I can also correctly connect.

Judging by your YAML, you seem to be using Kubernetes (since `docker-compose`'s way of defining env vars doesn't look like that)... The only thing I can think of is that something else could be setting the `PORT` environment variable thus ignoring the one you defined in your manifest. 

I tried checking if by default Kubernetes would do that but running a simple Nginx pod showed me there were no `PORT` variables set. Trying to run `docker-http-server` in Kubernetes also seems to work correctly:

```bash
$ kubectl run http-server --image=ghcr.io/patrickdappollonio/docker-http-server --env PORT=1234 --port=1234
pod/http-server created
```

Describing it shows the environment variable correctly set...

```bash
kubectl get pod http-server -o yaml | grep spec -A5
```

```yaml
spec:
  containers:
  - env:
    - name: PORT
      value: "1234"
    image: ghcr.io/patrickdappollonio/docker-http-server
```

And then the logs of the container also shows it's listening on this custom port:

```bash
$ kubectl logs http-server
2023/01/19 07:02:01 SETUP:
2023/01/19 07:02:01  > Configured to use port: 1234
2023/01/19 07:02:01  > Serving path: ./
2023/01/19 07:02:01 Starting server...
```

With all that, I'm not sure this would be a bug in `http-server` without having more information. Happy to discuss it further either here or privately if you would rather not expose a Kubernetes manifest you don't feel confident sharing in public. My social media is in my profile alongside [my website](https://www.patrickdap.com/) (which has a few other methods to communicate with me in the footer as well). In any case, please do let me know! 

If you can share a bit more of your setup, that might help us shed some light into it.

One thing to note: `PORT` is quite a common environment variable. If, for any reason, your stack is hijacking it to be used elsewhere (say, you're using something like multi-stage builds where your last stage might override the `PORT` variable) then chances are you will either have to account for this or configure it in a different way.

Here are two options:

* [medium complexity] [Use a configuration file](README.md#configuration-provided-via-config-files); or...
* [easy] Configure it via the flag, by overriding the `command` and `args` fields. Example below:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: http-server
spec:
  containers:
  - name: http-server
    image: ghcr.io/patrickdappollonio/docker-http-server:v2.0.0
    command: ["/docker-http-server"]
    args: ["--port=1234"]
```

You can still define the rest of the arguments via env vars.

This also tempts me to add an alias for `PORT` called `HTTP_SERVER_PORT`. We're doing that for older environment variables from versions 1.x to maintain backwards compatibility.

Let me know how it goes!
